version: '3.8'
services:
  patient-service:
    build: ./  # Spécifie le répertoire où se trouve le Dockerfile de patient-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"

volumes:
  mongo-data:  # Déclare un volume persistant pour MongoDB
